version: '3'

services:
  generator:
    image: my-registry:55000/gen:ci-${GENERATOR_BUILD_NUMBER-10}
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8081:8025" 
    #-- ports: are not required as containers use private network,
    # these have only been used for host o/s testing
